data:
  root: "./dataset/"
  train_dir: "train"
  test_dir: "test"
  raw_dir: "Imgs"
  mask_dir: "GT"
  image_size: 384
  extensions: [".png", ".jpg", ".jpeg", ".bmp", ".tiff"]

model:
  encoder: 
    patch_size: [7, 3, 3, 0.5, 0.5]
    embed_dims: [64, 128, 320, 128, 64]
    num_heads: [1, 2, 5, 2, 1]
    mlp_ratios: [4, 4, 4, 4, 4]
    qkv_bias: True
    depths: [3, 6, 40, 6, 3]
    sr_ratios: [8, 4, 2, 1, 1]
    drop_rate: 0.0
    drop_path_rate: 0.1
  in_ch: 3 
  d_h: 128 
  p_h: 8 
  s_h: 4 
  d_l: 128 
  p_l: 32 
  window_size: 7
  

training:
  model_dir: "./outputs_COD/"
  epochs: 100

  optimizer:
    name: "AdamW"
    lr: 0.0003
    weight_decay: 0.0001
    betas: [0.9, 0.999]

  scheduler:
    name: "CosineAnnealingLR"
    T_max: 100
    eta_min: 0.00001